server:
  port: 8888
spring:
  application:
    name: myconsulserver
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: myconsul-id001
        health-check-path: /actuator/health
        health-check-timeout: 10s
        register-health-check: true
management:
  endpoints:
    web:
      exposure:
        include: "*"